strings:
  inputs: "../SubsCraft/Sources/SubsCraftResources/Resources/Localizations/en.lproj"
  outputs:
    - templatePath: module.strings.stencil
      output: ../SubsCraft/Sources/SubsCraftResources/Generated/L10n.generated.swift
      params:
        enumName: L10n
        publicAccess: true
xcassets:
  inputs: "../SubsCraft/Sources/SubsCraftResources/Resources/Assets.xcassets"
  outputs:
    - templatePath: module.assets.stencil
      output: ../SubsCraft/Sources/SubsCraftResources/Generated/Assets.generated.swift
      params:
        enumName: Assets
        publicAccess: true
