require 'babelish'
require 'json'
require 'date'

default_platform(:ios)

import_from_git(
  url: 'git@github.com:appstea/Fastlane_Actions.git', 
  path: 'Fastfile',
)

lane :update_l10n do
  system('babelish csv2strings')

  system('rm -rf ../Sources/SubsCraftResources/Resources/Localizations')
  system('mkdir ../Sources/SubsCraftResources/Resources/Localizations')
  system('rsync -av --exclude=\'InfoPlist.strings\' ../Localizations/ ../Sources/SubsCraftResources/Resources/Localizations')

  codegen()
end

lane :codegen do
  swiftgen_l10n = 'swiftgen config run --config ../SwiftGen/.swiftgen.yml'
  system(swiftgen_l10n)
end